language: java
jdk: openjdk8
git:
  depth: false

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - script: sbt publishLocal

#   - name: "Readme"
#     script: amm scripts/generate-readme.sc

  - stage: release
    script:
      - sbt ci-release

before_install:
- export PATH="$HOME/.bin:$PATH"
- ./scripts/.travis-setup.sh

# deploy:
#   provider: pages
#   skip_cleanup: true
#   keep_history: true
#   github_token: $GH_TOKEN
#   target_branch: master
#   on:
#     branch: master

cache:
  directories:
  - $HOME/.bin
  - $HOME/.cache
  - $HOME/.sbt
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
